### PR TITLE
Armenr/provisioner improvements

### PR DESCRIPTION
**Pull request by armenr**
The ansible-local.py is not forward-compatible with new versions of Ansible. As it is, accessing the Ansible API And assembling the inventory object the way that was being done is not wise. That script is a very nice hack, but it won't go the distance. 

This wouldn't scale and is very brittle. 

In this new paradigm, many, many problems are addressed. I will make note of them all.

### CODE REVIEW

**Comment by ravibhure** [comment]
@armenr  thank you for PR, could you please update the readme with the updated example and related changes.

**Comment by armenr** [comment]
Sorry. This is not ready. It was opened by mistake! It is actually not working right yet. I opened it against your repo by accident. 

Apologies!

**Comment by armenr** [comment]
Could you please delete this PR?

**Comment by ravibhure** [comment]
@armenr, sure thing.
Good work, please resend the PR once done!

**Pull request closed without merging**
